---
- name: Install BCM10 head node (Ansible add-on)
  hosts: localhost
  become: true
  connection: local
  gather_facts: true

  roles:
    - role: brightcomputing.installer100.head_node
      vars:
        # ── Mandatory license/product parameters ──
        install_medium: "dvd"
        install_medium_dvd_path: "/home/ubuntu/bcm-10.0-ubuntu2404.iso"
        product_key: "XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX"
        license:
          country: "US"
          state: "Massachusetts"
          locality: "Boston"
          organization: "AHEAD"
          organizational_unit: "HPC"
          cluster_name: "mgburn"
          mac: "0a:ff:e2:16:bf:9f"
        db_cmd_password: "ahead"
        management_interface: "ahead"
        ldap_root_pass: "ahead"
        ldap_readonly_pass: "ahead"
        slurm_user_pass: "ahead"

